[package]
name = "rust-proptest"
version = "0.1.0"
edition = "2024"
repository = "https://github.com/AntoniosBarotsis/rust-proptest"
license = "GPL-3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proptest = "1.6.0"
