name: Build Gradle Project

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/kotlin-kotest.yaml
      - kotlin-kotest/**
  pull_request:
    branches:
      - master
    paths:
      - .github/workflows/kotlin-kotest.yaml
      - kotlin-kotest/**

defaults:
  run:
    working-directory: kotlin-kotest

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Validate Gradle wrapper'
        uses: gradle/actions/wrapper-validation@v4
      - name: "Setup JDK temurin"
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
      - name: "Setup Gradle"
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.10.2
      - name: 'Build'
        run: gradle assemble testClasses
      - name: 'Test'
        run: gradle check

