name: Build Rust Project (proptest)

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/rust-proptest.yaml
      - rust-proptest/**
  pull_request:
    branches:
      - master
    paths:
      - .github/workflows/rust-proptest.yaml
      - rust-proptest/**

defaults:
  run:
    working-directory: rust-proptest

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Use cached dependencies
        uses: Swatinem/rust-cache@v2
        with:
          key: "ubuntu-24.04-x86_64-unknown-linux-gnu"

      - name: Build
        run: cargo build --verbose

      - name: Test
        run: cargo test --verbose

  lint:
    name: Lint
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use cached dependencies
        uses: Swatinem/rust-cache@v2
        with:
          key: "ubuntu-24.04-x86_64-unknown-linux-gnu"

      - name: Install clippy and rustfmt
        run: |
          rustup component add clippy
          rustup component add rustfmt

      - name: Run clippy
        run: cargo clippy --all-features -- -Dwarnings

      - name: Run fmt
        run: cargo fmt --check



