name: Build Rust Project (quickcheck)

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/rust-quickcheck.yaml
      - rust-quickcheck/**
  pull_request:
    branches:
      - master
    paths:
      - .github/workflows/rust-quickcheck.yaml
      - rust-quickcheck/** 

defaults:
  run:
    working-directory: rust-quickcheck

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Use cached dependencies
        uses: Swatinem/rust-cache@v2
        with:
          key: "ubuntu-24.04-x86_64-unknown-linux-gnu"

      - name: Build
        run: cargo build --verbose

      - name: Test
        run: cargo test --verbose

